### ISSUE TITLE
Question: How to upgrade notary client to work for signer/server 0.3.0?

### ISSUE THREAD

**Issue by LenutaToderean** [docker/notary-official-images#3]
Hi! 
I installed notary using:

>sudo apt-get update
>sudo apt-get install notary

I need for a latest version of notary client in order to add delegates. I am trying to update my notary client  and I didn't manage to do this. I am using 0.3.0 images for notary server/signer. Any small information will be very usefully.  The documentation in the official site is not available (see below). Thank you!

![image](https://cloud.githubusercontent.com/assets/19945972/19427095/4dcc7c52-944a-11e6-8162-42e4ba410d45.png)

**Comment by LenutaToderean** [comment]
![image](https://cloud.githubusercontent.com/assets/19945972/19427085/3ac27a1c-944a-11e6-9b31-f0141e74d18b.png)

**Comment by HuKeping** [comment]
I think the best way is to get it from the release page of notary, which would like be:

https://github.com/docker/notary/releases

**Comment by LenutaToderean** [comment]
I tried this but I still cannot use the delegates.

notary --help
Notary allows the creation and management of collections of signed targets, allowing the signing and validation of arbitrary content.

Usage:
  notary [command]

Available Commands:
  version     Print the version number of notary
  key         Operates on keys.
  cert        Operates on certificates.
  init        Initializes a local trusted collection.
  list        Lists targets for a remote trusted collection.
  add         Adds the file as a target to the trusted collection.
  remove      Removes a target from a trusted collection.
  status      Displays status of unpublished changes to the local trusted collection.
  publish     Publishes the local trusted collection.
  lookup      Looks up a specific target in a remote trusted collection.
  verify      Verifies if the content is included in the remote trusted collection

Flags:
  -c, --configFile string   Path to the configuration file to use
  -s, --server string       Remote trust server location
  -d, --trustDir string     Directory where the trust data is persisted to
  -v, --verbose             Verbose output

Use "notary [command] --help" for more information about a command.

**Comment by HuKeping** [comment]
Any steps please?

**Comment by LenutaToderean** [comment]
sudo mkdir /usr/local/notary_client
cd /usr/local/notary_client
sudo wget https://github.com/docker/notary/archive/v0.3.0-RC5.tar.gz
sudo tar -C /usr/local/ -xzf v0.3.0-RC5.tar.gz
sudo rm v0.3.0-RC5.tar.gz

notary --help
=> The program 'notary' is currently not installed. You can install it by typing:
sudo apt install notary

If I use "sudo apt install notary" => version 0.1 is installed.

**Comment by HuKeping** [comment]
Please try 
```
$ wget https://github.com/docker/notary/releases/download/v0.4.2/notary-Linux-amd64
$ chmod +x notary-Linux-amd64

$ ./notary-Linux-amd64 --help

```

**Comment by LenutaToderean** [comment]
@HuKeping ...Thank you very much! Really appreciate your help!

**Comment by LenutaToderean** [comment]
Hi, again!
I managed to generate and add delegation. I am trying to push signed images from machine B to A machine's  registry. On machine A I have notary up and running but on B, I don't. When I push from B -> A with DOCKER_CONTENT_TRUST enabled I receive:  "Error: trust data missing for remote repository mydomain.com:5000/ubuntu or remote repository not found: timestamp key trust data unavailable.  Has a notary repository been initialized? ".  My new question is I must have the notary service up and running on machine B in order to push signed images?

**Comment by HuKeping** [comment]
Hi, would you mind if file this issue to https://github.com/docker/notary/issues ?
