### ISSUE TITLE
0.6.0 is out!

### ISSUE THREAD

**Issue by justincormack** [docker/notary-official-images#4]
notary 0.6.0 is now out, but the images are not updated yet.

**Comment by aj-jaswanth** [comment]
Hi @justincormack. Same here. *0.6.1* is out now.

**Comment by lag-linaro** [comment]
Looks like this can be closed now.

**Comment by justincormack** [comment]
No, there are still no images for 0.6 or 0.6.1 https://hub.docker.com/_/notary/
